all:
  hosts:
    node1:
      ansible_host: 10.20.206.60
      ip: 10.20.206.60
      access_ip: 10.20.206.60
      ansible_user: dba
      ansible_connection: ssh
      ansible_port: 22
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    node2:
      ansible_host: 10.20.206.61
      ip: 10.20.206.61
      access_ip: 10.20.206.61
      ansible_user: dba
      ansible_connection: ssh
      ansible_port: 22
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    node3:
      ansible_host: 10.20.206.62
      ip: 10.20.206.62
      access_ip: 10.20.206.62
      ansible_user: dba
      ansible_connection: ssh
      ansible_port: 22
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    node4:
      ansible_host: 10.20.206.77
      ip: 10.20.206.77
      access_ip: 10.20.206.77
      ansible_user: dba
      ansible_connection: ssh
      ansible_port: 22
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
