apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ops-mangaer-binding1
  namespace: ns-ops
subjects:
- kind: User
  name: ops1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ops-manager1
  apiGroup: rbac.authorization.k8s.io