apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-manager-bindig
  namespace: ns-dev
subjects:
- kind: User
  name: dev1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-manager
  apiGroup: rbac.authorization.k8s.io